<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN"
   "http://www.w3.org/TR/html4/strict.dtd">

<html lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
	<title>AutoNetkit Network Summary</title>
</head>
<body>                   
<h1>AutoNetkit Network Summary</h1>        

<h2>Network Statistics</h2>
	<table>
		<tr> <th>Total Routers:</th> <td>${network_stats['node_count']}</td> </tr>     
		<tr> <th>Total Links:</th> <td>${network_stats['edge_count']}</td> </tr>       
		<tr> <th>Autonomous Systems:</th> <td>${network_stats['as_count']}</td> </tr>                         
	</table>
  
  Generated by <a href="http://packages.python.org/AutoNetkit/">AutoNetkit</a>
</body>
</html>
